{{- if .Values.config.env.sealed }}
  {{- if .Values.config.env.existingSecret }}
    {{- fail "You cannot use both existingSecret and sealed in config.env" }}
  {{- end }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "unpackerr.fullname" . }}-env
spec:
  encryptedData:
    {{- range $key, $value := .Values.config.env.sealed }}
    {{ $key }}: {{ splitList "\n" $value | join "" }}
    {{- end }}
{{- end }}
{{- if .Values.config.file.sealed }}
  {{- if .Values.config.file.existingSecret }}
    {{- fail "You cannot use both existingSecret and sealed in config.file" }}
  {{- end }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "unpackerr.fullname" . }}-config-file
spec:
  encryptedData:
    unpackerr.conf: {{ splitList "\n" .Values.config.file.sealed | join "" }}
{{- end }}
