{{- include "mediamtx.validate" . }}
{{- if .Values.auth.sealed }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "mediamtx.fullname" . }}-auth
  labels:
    {{- include "mediamtx.labels" . | nindent 4 }}
spec:
  encryptedData:
    {{- range $key, $value := .Values.auth.sealed }}
    {{ $key }}: {{ $value | nospace | quote }}
    {{- end }}
{{- end }}
