{{- if .Values.secretEnv.sealed }}
{{- if .Values.secretEnv.existingSecret }}
{{- fail "You cannot use both existingSecret and sealed in secretEnv" }}
{{- end }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "mediamtx.fullname" . }}-env
  labels:
    {{- include "mediamtx.labels" . | nindent 4 }}
spec:
  encryptedData:
    {{- range $key, $value := .Values.secretEnv.sealed }}
    {{ $key }}: {{ splitList "\n" $value | join "" }}
    {{- end }}
{{- end }}
