{{- $ports := include "mediamtx.httpPorts" . | fromYamlArray }}
{{- if $ports }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mediamtx.fullname" . }}-http
  labels:
    {{- include "mediamtx.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.httpService.annotations | nindent 4 }}
spec:
  type: {{ .Values.httpService.type }}
  {{- with .Values.httpService.externalTrafficPolicy }}
  externalTrafficPolicy: {{ . }}
  {{- end }}
  ports:
    {{- range $ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .name }}
      protocol: {{ .protocol }}
    {{- end }}
  selector:
    {{- include "mediamtx.selectorLabels" . | nindent 4 }}
{{- end }}
