apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ddclient.fullname" . }}
  labels:
    {{- include "ddclient.labels" . | nindent 4 }}
data:
  ddclient.conf: |
    {{- tpl .Values.config.template . | nindent 4 }}
