# {{ required "image.repository needs to be defined!" .Values.image.repository }}
# {{ required "service.port needs to be defined!" .Values.service.port }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "mumble.fullname" . }}
  labels:
    {{- include "mumble.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "mumble.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "mumble.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- toYaml .Values.podAnnotations | nindent 8 }}
      labels:
        {{- include "mumble.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- toYaml .Values.env | nindent 12 }}
          ports:
            - name: mumble-tcp
              containerPort: {{ .Values.mumble.port }}
              protocol: TCP
            - name: mumble-udp
              containerPort: {{ .Values.mumble.port }}
              protocol: UDP
            {{- with .Values.extraPorts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: {{ .Values.mumble.dataDirPath }}

            {{- if .Values.mumble.config }}
            - name: mumble-config
              mountPath: /data/mumble-server.ini
              subPath: mumble-server.ini
            {{- end }}

            {{- with .Values.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      volumes:
        - name: data
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: data
          {{- else }}
          emptyDir: {}
          {{- end }}

        {{- if .Values.mumble.config }}
        - name: mumble-config
          configMap:
            name: {{ include "mumble.fullname" . }}-config
        {{- end }}

        {{- with .Values.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}

      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}

  volumeClaimTemplates:
    {{- if .Values.persistence.enabled }}
    - name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
        storageClassName: {{ .Values.persistence.storageClass }}
    {{- end }}

    {{- with .Values.extraVolumeClaimTemplates }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
