name: Helm

on:
  pull_request: {}
  push:
    branches: [ master ]

jobs:
  unittest:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run helm unittest
        uses: d3adb5/helm-unittest-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
